### ISSUE TITLE
DISPLACEMENT

### ISSUE THREAD

**Issue by nicejava** [Morita-Daiki/cudaSamplingMoire#2]
I need calculate displacement. From like this

![image](https://github.com/Morita-Daiki/cudaSamplingMoire/assets/6760497/4f7e4165-f38d-4c5f-97ce-1a2cc7179ea6)

How to do with vc++ coding ?

**Comment by Morita-Daiki** [comment]
In [this code](https://github.com/Morita-Daiki/cudaSamplingMoire/blob/dd70584b80c0fe25fb343b472ef67f9d743afac5/SamplingMoire/src/main.cpp#L131C1-L137C62),It caluculates eq(2) except arctangent.

And I just caluculate the phase at [here](https://github.com/Morita-Daiki/cudaSamplingMoire/blob/dd70584b80c0fe25fb343b472ef67f9d743afac5/SamplingMoire/src/main.cpp#L147)
But I didn't caluculate displacement. Because I needed only Phase fluctuation.

If you want to calculate displacement then,
1. get a first phase Image as reference
2. Calculate phase difference(eq 3?)
3. add difference phase to reference phase(eq 4?)
4. Multiply by the distance coefficient that maps the phase onto real space(It depends Camera parameters, stripe spacing, sampling interval, etc.)

I am not a vc++ expert so I can't give you specific advice, but you should check the paper and step by step and write your code.

**Comment by Morita-Daiki** [comment]
Also, I would like you to give me a doi link when you tell me your paper.
Because I am Japanese and not good at English.
Images aren't good for machine translation.((´∀｀))
